### ISSUE TITLE
v1.2 - Todo

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez#575]
- [ ] Un bug à fix sur les usage, on voit pas les crédits restants si jamais on a pas déjà utiliser l'app au moins une fois
- [ ] Autre bug dans la page usage si jamais on a utiliser plusieurs token d'api, on a pas le vrai descriptif 
- [ ] Adapter la page de playground
- [ ] Adapter le readme 
- [ ] Adapter la doc.forvoyez
- [ ] Adapter le plugin wordpress
- [ ] Ajouter dans la landing la partie sur le plugin wordpress
- [ ] Adapter le plugin Strapi + finir plugin strapi 
- [ ] Comm autour du plugin strapi 
- [ ] Adapter la doc.forvoyez (ajouter plugin strapi) 
- [ ] Ajouter dans la landing la partie sur le plugin strapi 
- [ ] Proposer plugin strapi officiel (store strapi) 
- [ ] Product hunt plugin strapi
